# # configs/metrics.yaml
# # ---------- Gauges ----------
# fps_vidcap:                "avg_over_time(vidcap_fps[1m])"
# fps_vidcap_avg:            "avg_over_time(vidcap_fps_avg[1m])"
# vidcap_delay_gauge:        "avg_over_time(vidcap_delay[1m])"
# inference_time_micros_gauge: "avg_over_time(inference_time_micros[1m])"

# # ---------- Histograms ----------
# kafka_delay_p90:           "histogram_quantile(0.9, sum(rate(ml_to_backend_kafka_delay_bucket[1m])) by (le))"
# kafka_delay_mean:          "sum(rate(ml_to_backend_kafka_delay_sum[1m])) / sum(rate(ml_to_backend_kafka_delay_count[1m]))"

# db_delay_p90:              "histogram_quantile(0.9, sum(rate(db_insert_delay_bucket[1m])) by (le))"
# db_delay_mean:             "sum(rate(db_insert_delay_sum[1m])) / sum(rate(db_insert_delay_count[1m]))"

# common_delay_p90:          "histogram_quantile(0.9, sum(rate(common_event_delay_bucket[1m])) by (le))"   # ← целевая
# heartbeat_delay_p90:       "histogram_quantile(0.9, sum(rate(heartbeat_delay_bucket[1m])) by (le))"
# common_cad:                'common_cad{instance="consumer_from_ws_with_metrics:8000", job="consumer_from_ws_with_metrics", service="castle"}'
common_cad_avg1h:                'avg_over_time(common_cad{instance="consumer_from_ws_with_metrics:8000", job="consumer_from_ws_with_metrics", service="castle"}[1h])'
db_insert_cad_avg1h:             'avg_over_time(db_insert_cad{instance="10.201.92.176:8010", job="consumer_ml_to_db", service="castle"}[1h])'
kafka_network_cad_avg1h:         'avg_over_time(kafka_network_cad{instance="10.201.92.176:8010", job="consumer_ml_to_db", service="castle"}[1h])'
counter_events_total:            'counter_events_total{instance="consumer_from_ws_with_metrics:8000", job="consumer_from_ws_with_metrics", service="castle"}'

# seq_health_bad_ratio:      "1 - histogram_quantile(0.0, sum(rate(seq_events_health_bucket[1m])) by (le))" # доля некорректных

# # ---------- Counters ----------
# heartbeat_per_sec:         "rate(heartbeat_counter_total[1m])"
# events_per_sec:            "rate(event_counter_total[1m])"
